# Generated by Django 5.2.5 on 2026-08-10 14:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("assistant_name", models.CharField(default="Assistant", max_length=100)),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="If blank, a default prompt is built from the business's own profile at reply time.",
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("friendly", "Friendly"),
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("formal", "Formal"),
                        ],
                        default="friendly",
                        max_length=20,
                    ),
                ),
                ("welcome_message", models.TextField(blank=True)),
                (
                    "fallback_message",
                    models.TextField(
                        default="I'm not sure about that — let me get a member of our team to help you."
                    ),
                ),
                ("max_response_length", models.PositiveIntegerField(default=500)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ai", "AI-only"),
                            ("human", "Human-only"),
                            ("hybrid", "Hybrid (AI with handoff)"),
                        ],
                        default="hybrid",
                        max_length=10,
                    ),
                ),
                ("ai_enabled", models.BooleanField(default=True)),
                ("human_handoff_enabled", models.BooleanField(default=True)),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.6,
                        help_text="Below this, hand off to a human even if human_handoff_enabled.",
                    ),
                ),
                (
                    "handoff_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Case-insensitive substrings — a customer message containing any of these forces handoff.",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        default="openai",
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="If blank, a sensible per-provider default is used.",
                        max_length=100,
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_settings",
                "indexes": [
                    models.Index(fields=["tenant"], name="ai_settings_tenant__7c7ea1_idx")
                ],
            },
        ),
    ]
