# Generated by Django 5.2.5 on 2026-08-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("ai", "AI Assistant"),
                    ("system", "System"),
                    ("campaign", "Campaign"),
                ],
                max_length=20,
            ),
        ),
    ]
