# Generated by Django 5.2.5 on 2026-08-11 07:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login_user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret_encrypted",
            field=models.CharField(
                blank=True,
                help_text="Fernet-encrypted TOTP secret — see core.crypto.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_mfa_backup_code",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "code_hash"), name="unique_backup_code_hash_per_user"
                    )
                ],
            },
        ),
    ]
