# Generated by Django 5.2.5 on 2026-08-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="marketing_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="marketing_opt_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
