# Generated by Django 5.2.5 on 2026-08-10 11:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("electronics", "Electronics"),
                            ("fashion", "Fashion & Apparel"),
                            ("food_beverage", "Food & Beverage"),
                            ("health_beauty", "Health & Beauty"),
                            ("services", "Professional Services"),
                            ("education", "Education"),
                            ("agriculture", "Agriculture"),
                            ("real_estate", "Real Estate"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Kenya", max_length=100)),
                ("timezone", models.CharField(default="Africa/Nairobi", max_length=50)),
                ("currency", models.CharField(default="KES", max_length=3)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="businesses/logos/"),
                ),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "businesses_business",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="businesses__tenant__c567d9_idx",
                    )
                ],
            },
        ),
    ]
